services:
  devcontainer:
    extends: # see: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
      file: ./base/docker-compose.yaml
      service: devcontainer

  mailpit:
    container_name: ${APP_NAME}-mailpit
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost:8025/livez"]
      retries: 3
      timeout: 5s
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    restart: unless-stopped

  meilisearch:
    extends: # see: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
      file: ./base/docker-compose.yaml
      service: meilisearch

  mysql:
    extends: # see: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
      file: ./base/docker-compose.yaml
      service: mysql

  # TODO: timezone is probably still set to UTC
  frankenphp: # PHP 8.2+
    build:
      context: .
      dockerfile: ./frankenphp/Dockerfile
    container_name: ${APP_NAME}-frankenphp
    environment:
      - XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal output_dir=/tmp/xdebug profiler_output_name=cachegrind.out.%R.%u}
    extra_hosts:
      - "host.docker.internal:host-gateway" # for accessing the host from inside the container
    ports:
      - ${FORWARD_PHP_HTTP_PORT:-80}:80
      - ${FORWARD_PHP_HTTPS_PORT:-443}:443
    restart: unless-stopped
    working_dir: /app

  phpmyadmin:
    extends: # see: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
      file: ./base/docker-compose.yaml
      service: phpmyadmin

  redis:
    extends: # see: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
      file: ./base/docker-compose.yaml
      service: redis

  soketi:
    container_name: ${APP_NAME}-soketi
    environment:
      - SOKETI_DEBUG=${SOKETI_DEBUG:-1}
      - SOKETI_METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET}
    image: quay.io/soketi/soketi:latest
    ports:
      - ${PUSHER_FRONTEND_PORT:-6001}:6001
      - ${PUSHER_METRICS_PORT:-9601}:9601
    restart: unless-stopped

  webgrind:
    container_name: ${APP_NAME}-webgrind
    image: jokkedk/webgrind:latest
    ports:
      - ${FORWARD_WEBGRIND_PORT:-8080}:80
    restart: unless-stopped
